server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
      
spring:
  application:
    name: zcp-alertmanager
  output:
    ansi:
      enabled: always
  profiles:
    active: local
  session:
    store-type: none

---
spring:
  profiles: local

props:
  appName: zcp-alertmanager-local
  alertManager:
    baseUrl: http://alertmanager.zcp-dev.jp-tok.containers.mybluemix.net
    configMap: test-alertmanager
    namespace: monitoring
  prometheus:
    baseUrl: http://prometheus.zcp-dev.jp-tok.containers.mybluemix.net
    configMap: prometheus-user-rules
    namespace: monitoring
  redis:
    database: 0
    host: 169.56.100.62
    port: 32000
  
---
spring:
  profiles: dev

props:
  appName: zcp-alertmanager-dev
  alertManager:
    baseUrl: http://alertmanager-service:9093
    configMap: test-alertmanager
    namespace: monitoring
  prometheus:
    baseUrl: http://prometheus-service:9090
    configMap: prometheus-user-rules
    namespace: monitoring
  redis:
    database: 0
    host: 169.56.100.62
    port: 32000
