server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
      
spring:
  application:
    name: zcp-alertmanager
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

---
spring:
  profiles: local

props:
  appName: zcp-alertmanager-local
  alertManager:
    baseUrl: http://alertmanager.zcp-dev.jp-tok.containers.mybluemix.net
    configMap: test-alertmanager
    namespace: monitoring
  prometheus:
    baseUrl: http://prometheus.zcp-dev.jp-tok.containers.mybluemix.net
    configMap: prometheus-user-rules
    namespace: monitoring
  mariaDB:
    url: jdbc:mariadb://169.56.100.62:30000/alertmanager
    id: root
    password: admin
    
---
spring:
  profiles: dev

props: 
  appName: zcp-alertmanager-dev
  alertManager:
    baseUrl: http://alertmanager.cloudzcp.io
    configMap: alertmanager
    namespace: zcp-system
  prometheus:
    baseUrl: http://prometheus.cloudzcp.io
    configMap: prometheus-user-rules
    namespace: zcp-system
  mariaDB:
    url: jdbc:mariadb://169.56.100.62:30000/alertmanager
    id: root
    password: admin     

---
spring:
  profiles: stage

props:
  appName: zcp-alertmanager-stage
  alertManager:
    baseUrl: ${ALERT_BASE_URI}
    configMap: ${ALERT_CONFIGMAP}
    namespace: ${zcp-system}
  prometheus:
    baseUrl: ${PROMET_BASE_URI}
    configMap: ${PROMET_CONFIGMAP}
    namespace: ${zcp-system}
  mariaDB:
    url: ${MARIADB_URI}
    id: ${MARIADB_ID}
    password: ${MARIADB_PWD}
    