server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
      
spring:
  application:
    name: zcp-alertmanager
  output:
    ansi:
      enabled: always
  profiles:
    active: stage

---
spring:
  profiles: dev

props: 
  appName: zcp-alertmanager-dev
  alertManager:
    baseUrl: http://alertmanager.cloudzcp.io
    configMap: alertmanager
    namespace: zcp-system
  prometheus:
    baseUrl: http://prometheus.cloudzcp.io
    configMap: prometheus-user-rules
    namespace: zcp-system
  mariaDB:
    url: jdbc:mariadb://169.56.100.62:30000/alertmanager
    id: root
    password: admin     

---
spring:
  profiles: stage

props:
  appName: zcp-alertmanager-stage
  alertManager:
    baseUrl: http://alertmanager-service:9093
    configMap: alertmanager
    namespace: zcp-system
  prometheus:
    baseUrl: http://prometheus-service:9090
    configMap: prometheus-user-rules
    namespace: zcp-system
  mariaDB:
    url: jdbc:mariadb://webhook-mariadb:3306/alertmanager
    id: root
    password: admin   
    