apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-06-17T15:20:30Z
  generation: 78
  labels:
    component: zcp-alertmanager
  name: zcp-alertmanager
  namespace: zcp-system
  resourceVersion: "3532821"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/zcp-alertmanager
  uid: f8ed2ca2-7241-11e8-b76a-36b8e2896cc4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: zcp-alertmanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: zcp-alertmanager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - management
      containers:
      - envFrom:
        - configMapRef:
            name: zcp-alertmanager-config
        image: cloudzcp/zcp-alertmanager
        imagePullPolicy: Always
        name: zcp-alertmanager
        ports:
        - containerPort: 8080
          name: cont-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-26T05:21:07Z
    lastUpdateTime: 2018-07-26T05:21:07Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-06-17T15:20:30Z
    lastUpdateTime: 2018-07-26T05:21:07Z
    message: ReplicaSet "zcp-alertmanager-789b48d6bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 78
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
