apiVersion: v1
kind: ConfigMap
metadata:
  name: zcp-alertmanager-config
  namespace: zcp-system
data:
  SPRING_ACTIVE_PROFILE: stage
  ALERT_BASE_URI: http://alertmanager-service:9093
  ALERT_CONFIGMAP: alertmanager
  ALERT_NAMESPACE: zcp-system
  PROMET_BASE_URI: http://prometheus-service:9090
  PROMET_CONFIGMAP: prometheus-user-rules
  PROMET_NAMESPACE: zcp-system
  MARIADB_URI: jdbc:mariadb://alertmanager-store-mariadb:3306/alertmanager
