apiVersion: v1
data:
  users-rules.rules: |
    groups:
    - name: users-rules.rules
      rules:
      - alert: NodeCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu{component="node-exporter",mode="idle"}[5m])) * 100)) > 75
        for: 2m
        labels:
          severity: warning
          channel : first_receiver
        annotations:
          description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
      - alert: NodeCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu{component="node-exporter",mode="idle"}[5m])) * 100)) > 60
        for: 2m
        labels:
          severity: warning
          channel: second_receiver
        annotations:
          description: "{{$labels.instance}}: CPU usage is above 60% (current value is: {{ $value }})"
      - alert: NodeMemoryUsage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 10
        for: 2m
        labels:
          severity: warning
          channel: second_receiver
        annotations:
          description: "{{$labels.instance}}: Memory usage is above 10% (current value is: {{ $value }})"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"users-rules.rules":"groups:\n- name: users-rules.rules\n  rules:\n  - alert: NodeCPUUsage\n    expr: (100 - (avg by (instance) (irate(node_cpu{component=\"node-exporter\",mode=\"idle\"}[5m])) * 100)) \u003e 75\n    for: 2m\n    labels:\n      severity: warning\n      channel : first_receiver\n    annotations:\n      description: \"{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})\"\n  - alert: NodeCPUUsage\n    expr: (100 - (avg by (instance) (irate(node_cpu{component=\"node-exporter\",mode=\"idle\"}[5m])) * 100)) \u003e 60\n    for: 2m\n    labels:\n      severity: warning\n      channel: second_receiver\n    annotations:\n      description: \"{{$labels.instance}}: CPU usage is above 60% (current value is: {{ $value }})\"\n  - alert: NodeMemoryUsage\n    expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) \u003e 10\n    for: 2m\n    labels:\n      severity: warning\n      channel: second_receiver\n    annotations:\n      description: \"{{$labels.instance}}: Memory usage is above 10% (current value is: {{ $value }})\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-user-rules","namespace":"monitoring"}}
  creationTimestamp: 2018-05-31T06:10:26Z
  name: prometheus-user-rules
  namespace: monitoring
  resourceVersion: "2898054"
  selfLink: /api/v1/namespaces/monitoring/configmaps/prometheus-user-rules
  uid: 4fa3a99d-6499-11e8-915d-82c09a00d8d2
